wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'
  mode: 'disabled'  # Disable wandb for testing

experiment:
    project: "mmada-training-t2m"
    name: "mmada-training-t2m-instruct"
    output_dir: "mmada-training-t2m-instruct"
    save_every: 10
    eval_every: 5
    generate_every: 10
    log_every: 1
    log_grad_norm_every: 100
    resume_from_checkpoint: null  # Don't resume for testing
    val_every: 50

model:
    
    image_vq_model:
        type: "magvitv2"
        vq_model_name: "showlab/magvitv2"

    motion_vq_model:
        type: "vq"
        vq_model_name: "VQVAE"
        depth: 3
        dilation_growth_rate: 3
        nb_code: 512
        code_dim: 512
        output_emb_width: 512
        width: 512
        quantizer: "ema_reset"
        mu: 0.99
        resume_pth: "output/VQVAE/net_last.pth"

    mmada:
        tokenizer_path: "GSAI-ML/LLaDA-8B-Instruct"
        pretrained_model_path: "Gen-Verse/MMaDA-8B-MixCoT"
        w_clip_vit: False
        new_vocab_size: 135055  # Fixed: text (126349) + image (8192) + motion (512) + EOM (1) + PAD (1)
        llm_vocab_size: 126464
        image_codebook_size: 8192
        motion_codebook_size: 512
        num_vq_tokens: 256
        num_new_special_tokens: 0
        tie_word_embeddings: False

    gradient_checkpointing: True

dataset:
    gen_type: "t2m"
    params:
        dataset_name: "t2m"
        num_workers: 32
        down_t: 2
        stride_t: 2
        

    preprocessing:
        max_seq_length: 256 # for text tokens
        resolution: 256
        center_crop: False
        random_flip: False
        max_motion_length: 256

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 5e-5
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 5
        min_lr_scale: 0.1

training:
    gradient_accumulation_steps: 1
    noise_type: "mask"
    batch_size_t2m: 8
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 10086
    max_train_steps: 5
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: 1
    guidance_scale: 3
    generation_timesteps: 12
    t2i_coeff: 1.0
    lm_coeff: 0.1
    mmu_coeff: 0.5
    t2m_coeff: 1.0        # Motion training coefficient
    validation_seed: 42